default: main.cpp count-letters.cpp output-letters.cpp
	g++ -std=c++0x main.cpp count-letters.cpp output-letters.cpp -o ./lab2

zip:
	zip -D Lab2_Conty_Genevieve.zip *.cpp *.hpp makefile cupcake.txt

clean: $(CLEAN)
	rm lab2