default: main.cpp game.cpp loadedDie.cpp die.cpp validate.cpp
	g++ -std=c++0x main.cpp game.cpp loadedDie.cpp die.cpp validate.cpp -o ./lab3

zip:
	zip -D Lab4_Conty_Genevieve.zip *.cpp *.hpp makefile

clean: $(CLEAN)
	rm lab3