default: main.cpp building.cpp instructor.cpp person.cpp student.cpp university.cpp validate.cpp
	g++ -std=c++0x main.cpp building.cpp instructor.cpp person.cpp student.cpp university.cpp validate.cpp -o ./lab4

zip:
	zip -D Lab4_Conty_Genevieve.zip *.cpp *.hpp makefile

clean: $(CLEAN)
	rm lab4