default: main.cpp animal.cpp penguin.cpp tiger.cpp turtle.cpp zoo.cpp validation.cpp
	g++ main.cpp animal.cpp penguin.cpp tiger.cpp turtle.cpp zoo.cpp validation.cpp -o zoo

zip:
	zip -D zooLab *.hpp *.cpp makefile